 const DB_NAME = 'Shotlin';

 const CLOUDINARY_CLOUD_NAME="shotlin";
 const CLOUDINARY_API_KEY="452998463171572";
 const CLOUDINARY_API_SECRET="ycIqO_ahCJv_EHtiF5sk40EP-7E";


export {DB_NAME,CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET}