name: Deploy to VPS

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
              ssh -o StrictHostKeyChecking=no shotlin@159.89.169.204 "
              cd /home/shotlin/ShotlinBackend &&
              git pull &&
              npm install &&
              pm2 startOrRestart ./src/index.js
              "
